// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBwSqL5j80zbMWyKtxaF9fYWmkgCu_NImY',
    appId: '1:1074324118915:web:a51d2dafa2f0cf9d91eab6',
    messagingSenderId: '1074324118915',
    projectId: 'prometeo-520a2',
    authDomain: 'prometeo-520a2.firebaseapp.com',
    storageBucket: 'prometeo-520a2.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDvLpGesEXnc2am2dcctbGK53H7LNTsP7s',
    appId: '1:1074324118915:android:46014408c4f5436191eab6',
    messagingSenderId: '1074324118915',
    projectId: 'prometeo-520a2',
    storageBucket: 'prometeo-520a2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBYQ10JofsSoLi4wT_O1uXRahH4VXn8zUo',
    appId: '1:1074324118915:ios:bcc928c7b4c3244491eab6',
    messagingSenderId: '1074324118915',
    projectId: 'prometeo-520a2',
    storageBucket: 'prometeo-520a2.firebasestorage.app',
    iosBundleId: 'com.example.prometeo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBYQ10JofsSoLi4wT_O1uXRahH4VXn8zUo',
    appId: '1:1074324118915:ios:bcc928c7b4c3244491eab6',
    messagingSenderId: '1074324118915',
    projectId: 'prometeo-520a2',
    storageBucket: 'prometeo-520a2.firebasestorage.app',
    iosBundleId: 'com.example.prometeo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBwSqL5j80zbMWyKtxaF9fYWmkgCu_NImY',
    appId: '1:1074324118915:web:d08abd3cfd2a197891eab6',
    messagingSenderId: '1074324118915',
    projectId: 'prometeo-520a2',
    authDomain: 'prometeo-520a2.firebaseapp.com',
    storageBucket: 'prometeo-520a2.firebasestorage.app',
  );

}